---
name: Test artifact
on: 
  workflow_dispatch:

env:
  artifact_filename: artifact_body.txt
  artifact_path: ./artifacts/
  artifact_name: TestArtifact
  download_arifact_path: ./download_artifact/

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artefact
        run: |
          mkdir ${{env.artifact_path}}
          echo "Hello, World? This is artifact body!" > ${{env.artifact_path}}${{env.artifact_filename}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.artifact_name}}
          path: ${{env.artifact_path}}${{env.artifact_filename}}
  download_artifact:
    needs: upload_artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with: 
          name: ${{env.artifact_name}}
          path: ${{env.download_arifact_path}}
      - name: Print Artifact
        run: |
          ls ${{env.download_arifact_path}} -la
          echo "Artifact body =" && cat ${{env.download_arifact_path}}${{env.artifact_filename}}

